DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS post_tags CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uniq_users_email UNIQUE (email)
);

CREATE TABLE user_profiles (
  user_id INTEGER NOT NULL,
  bio TEXT,
  avatar_url VARCHAR(255) DEFAULT NULL,
  website VARCHAR(255) DEFAULT NULL,
  birthday DATE DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_user_profiles_user_id
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_posts_user_id
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_posts_user_id ON posts (user_id);

CREATE TABLE tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uniq_tags_name UNIQUE (name)
);

CREATE TABLE post_tags (
  post_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  PRIMARY KEY (post_id, tag_id),
  CONSTRAINT fk_post_tags_post_id
    FOREIGN KEY (post_id) REFERENCES posts (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_post_tags_tag_id
    FOREIGN KEY (tag_id) REFERENCES tags (id)
    ON DELETE CASCADE
);

CREATE INDEX idx_post_tags_tag_id ON post_tags (tag_id);

CREATE TABLE comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_comments_post_id
    FOREIGN KEY (post_id) REFERENCES posts (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_comments_user_id
    FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE INDEX idx_comments_post_id ON comments (post_id);
CREATE INDEX idx_comments_user_id ON comments (user_id);

CREATE TABLE events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  type VARCHAR(100) NOT NULL,
  payload JSONB DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_events_user_id
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_events_user_id_created_at ON events (user_id, created_at);

INSERT INTO users (id, name, email, active, created_at) VALUES
(1, 'John Doe', 'john@example.com', TRUE, '2026-05-07 11:15:21'),
(2, 'Jane Smith', 'jane@example.com', TRUE, '2026-05-07 11:15:21');

INSERT INTO user_profiles (user_id, bio, avatar_url, website, birthday, updated_at) VALUES
(1, 'Backend developer and database enthusiast.', 'https://example.com/avatars/john.png', 'https://john.example.com', '1990-04-12', '2026-05-07 11:20:00'),
(2, NULL, NULL, 'https://jane.example.com', NULL, NULL);

INSERT INTO posts (id, user_id, title, body, published, created_at) VALUES
(1, 1, 'Hello PostgreSQL', 'First demo post.', TRUE, '2026-05-07 11:15:21'),
(2, 2, 'Another Post', 'Second demo post.', FALSE, '2026-05-07 11:15:21');

INSERT INTO tags (id, name, created_at) VALUES
(1, 'postgresql', '2026-05-07 11:15:21'),
(2, 'golang', '2026-05-07 11:15:21'),
(3, 'mapper', '2026-05-07 11:15:21');

INSERT INTO post_tags (post_id, tag_id) VALUES
(1, 1),
(1, 2),
(2, 3);

INSERT INTO comments (id, post_id, user_id, body, created_at) VALUES
(1, 1, 2, 'Nice post!', '2026-05-07 11:25:00'),
(2, 2, 1, 'Thanks for sharing.', '2026-05-07 11:30:00');

INSERT INTO events (id, user_id, type, payload, created_at) VALUES
(1, 1, 'user.login', '{"ip": "127.0.0.1"}'::jsonb, '2026-05-07 11:15:21'),
(2, 2, 'post.created', '{"post_id": 2}'::jsonb, '2026-05-07 11:15:21');

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('posts', 'id'), COALESCE((SELECT MAX(id) FROM posts), 1));
SELECT setval(pg_get_serial_sequence('tags', 'id'), COALESCE((SELECT MAX(id) FROM tags), 1));
SELECT setval(pg_get_serial_sequence('comments', 'id'), COALESCE((SELECT MAX(id) FROM comments), 1));
SELECT setval(pg_get_serial_sequence('events', 'id'), COALESCE((SELECT MAX(id) FROM events), 1));
